# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "moonfly"
# Inserts a blank line between shell prompts
add_newline = false

format = """
$time $battery $memory_usage $cmd_duration
$python$directory
$sudo$character
"""

[c]
style = "green"

[git_branch]
style = "lavender"

[package]
style = "orange"

[perl]
style = "green"

[swift]
style = "red"

[terraform]
style = "purple"

[palettes.moonfly]
fern = "#87d787"
lavender = "#adadf3"
orange = "#f09479"
red = "#f07496"

[character]
success_symbol = '[󰋇](blue)'
error_symbol = '[󰋇](red)'

[sudo]
style = 'bright-red'
symbol = ' '
disabled = false
format = '[$symbol]($style)'

[battery]
disabled = false
format = '[$symbol$percentage]($style)'

[[battery.display]]
threshold = 10
style = 'red'
discharging_symbol = '󰁺 '
charging_symbol = '󰢜 '

[[battery.display]]
threshold = 25
style = 'red'
discharging_symbol = '󰁼 '
charging_symbol = '󰂇 '

[[battery.display]]
threshold = 50
style = 'yellow'
discharging_symbol = '󰁾 '
charging_symbol = '󰢝 '

[[battery.display]]
threshold = 75
style = 'fern'
discharging_symbol = '󰂀 '
charging_symbol = '󰢞 '

[[battery.display]]
threshold = 99
style = 'fern'
discharging_symbol = '󰂂 '
charging_symbol = '󰂋 '

[[battery.display]]
threshold = 100
style = 'fern'
discharging_symbol = '󰁹 '
charging_symbol = '󰂅 '

[memory_usage]
disabled = false
format = '[$symbol$ram_pct:$swap_pct]($style)'
threshold = -1
symbol = ' '
style = 'yellow'

[time]
disabled = false
format = '[ $time]($style)'
style = 'cyan'
time_format = '%I:%M:%S %p'
use_12hr = true
utc_time_offset = 'local'

[cmd_duration]
min_time = 0
format = '[󱦟 $duration](cyan)'
show_milliseconds = true

[directory]
truncation_length = 2
truncation_symbol = '…/'
format = '[$read_only]($read_only_style)[$path]($style)'
style = 'fern'
read_only = '(RO)'
read_only_style = 'red'

[python]
format = "[($virtualenv) ]($style)"
style = "yellow"
